export const sampleWords: string[] = [
  "(en) allé",
  "alléen",
  "alléer",
  "alléerne",
  "(an) avenue",
  "(en) boulevard",
  "boulevarden",
  "boulevarder",
  "boulevarderne",
  "(a) boulevard",
  "(et) afbud",
  "afbuddet",
  "afbud",
  "afbuddene",
  "(a) cancellation",
  "(en) afdeling",
  "afdelingen",
  "afdelinger",
  "afdelingerne",
  "(a) department/branch",
  "(et) afsnit",
  "afsnittet",
  "afsnit",
  "afsnittene",
  "(a) paragraph/(an) episode",
  "(en) aftale",
  "aftalen",
  "aftaler",
  "aftalerne",
  "(an) agreement",
  "(en) albue",
  "albuen",
  "albuer",
  "albuerne",
  "(an) elbow",
  "(an) elbow",
  "(et) album",
  "albummet",
  "albummer",
  "albummerne",
  "(an) album",
  "(en) allergi",
  "allergien",
  "allergier",
  "allergierne",
  "(an) allergy",
  "(an) allergy",
  "(en) altan",
  "altanen",
  "altaner",
  "altanerne",
  "(a) balcony",
  "(en) analytiker",
  "analytikeren",
  "analytikere",
  "analytikerne",
  "(an) analyst",
  "(en) anmeldelse",
  "anmeldelsen",
  "anmeldelser",
  "anmeldelserne",
  "(a) review/notification",
  "(et) ansigt",
  "ansigtet",
  "ansigter",
  "ansigterne",
  "(a) face",
];
